export const SET_PRELOADER = "SET_PRELOADER";
export const GET_DATA_WEATHER = "GET_DATA_WEATHER";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_SUCCESSFULY = "FETCH_SUCCESSFULY";
export const WEATHER_VISIBILITY = "WEATHER_VISIBILITY";
